"""create review findings table

Revision ID: 2d133f635cec
Revises: b2425dcb6b2d
Create Date: 2026-10-06 00:20:00.957745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d133f635cec'
down_revision: Union[str, Sequence[str], None] = 'b2425dcb6b2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_run_id', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(length=500), nullable=False),
    sa.Column('line', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('suggested_fix', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_run_id'], ['review_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_findings_category'), 'review_findings', ['category'], unique=False)
    op.create_index(op.f('ix_review_findings_review_run_id'), 'review_findings', ['review_run_id'], unique=False)
    op.create_index(op.f('ix_review_findings_severity'), 'review_findings', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_findings_severity'), table_name='review_findings')
    op.drop_index(op.f('ix_review_findings_review_run_id'), table_name='review_findings')
    op.drop_index(op.f('ix_review_findings_category'), table_name='review_findings')
    op.drop_table('review_findings')
    # ### end Alembic commands ###
