"""create review runs table

Revision ID: b2425dcb6b2d
Revises: f5b2ffa5c5da
Create Date: 2026-10-06 00:16:06.525998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2425dcb6b2d'
down_revision: Union[str, Sequence[str], None] = 'f5b2ffa5c5da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository', sa.String(length=255), nullable=False),
    sa.Column('pull_request_number', sa.Integer(), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_runs_repository'), 'review_runs', ['repository'], unique=False)
    op.create_index(op.f('ix_review_runs_status'), 'review_runs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_runs_status'), table_name='review_runs')
    op.drop_index(op.f('ix_review_runs_repository'), table_name='review_runs')
    op.drop_table('review_runs')
    # ### end Alembic commands ###
